### ISSUE TITLE
Provide use-package installation instructions

### ISSUE THREAD

**Issue by aspiers** [Elilif/org-heatmap#6]
I heard that `use-package` will be officially included in 29.2 (IIRC).  Even if this wasn't planned, I think it's well worth providing a snippet in the README for installation via this excellent macro.

**Comment by Elilif** [comment]
@aspiers  Thank you for your suggestion. If I missed anything, please let me know.

**Comment by aspiers** [comment]
Thanks looks great, and TIL about `use-package` supporting `:custom` - how did I miss that for so long! :laughing:

**Comment by aspiers** [comment]
BTW I had this for installing from github via straight.el:

```
(use-package org-heatmap
  :straight (:host github :repo "Elilif/org-heatmap")
  :after (org)
  :config
  (org-heatmap-mode))
```

Until #5 is resolved, it might be worth also including this kind of trick.
