### ISSUE TITLE
add a screenshot to README

### ISSUE THREAD

**Issue by LemonBreezes** [Elilif/org-heatmap#8]
A lot of people (including me) are in transit reading Reddit and find this package but have no way to try it out. It would be great to have a screenshot in the README so that I don't forget about it.

**Comment by Elilif** [comment]
There are already some screenshots in the [README](https://github.com/Elilif/org-heatmap?tab=readme-ov-file#screenshots), what kind of screenshot do you want?

**Comment by LemonBreezes** [comment]
> There are already some screenshots in the [README](https://github.com/Elilif/org-heatmap?tab=readme-ov-file#screenshots), what kind of screenshot do you want?  

Oh, now I see them. I didn't see them maybe because of the mobile network.
